name: senior
package: com.senior.app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  go_router: ^14.8.0
  url_strategy: ^0.3.0
  provider: ^6.1.2
  universal_html: ^2.2.4
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  flex_color_picker: ^3.6.0
  firebase_storage: ^12.4.2
  shared_preferences: ^2.5.1
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  syncfusion_flutter_calendar: ^28.2.5
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards/
    - assets/social media/
    - assets/images/
    - assets/svgs/
    - assets/icons/
