name: senior
package: com.google.firebase.senior.dem
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_svg: ^2.0.10+1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.5.1
  icons_flutter: ^0.0.4
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^28.1.33
  table_calendar: ^3.1.1
  firebase_messaging: ^15.1.6
  flex_color_picker: ^3.4.1
  image_picker: ^1.1.1
  flutter_material_color_picker: ^1.2.0
  firebase_storage: ^12.3.7
  firebase_storage_web: ^3.9.5
  file_picker: ^8.0.3
  webview_flutter: ^4.7.0
  uuid: ^4.4.0
  image_picker_for_web: ^3.0.4
  url_strategy: ^0.3.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards/
    - assets/social media/
    - assets/images/
    - assets/svgs/
    - assets/icons/