name: senior
package: com.senior.app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.1
  intl: ^0.20.1
  url_strategy: ^0.3.0
  logger: ^2.5.0
  google_sign_in_web: ^0.12.4+3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards/
    - assets/social media/
    - assets/images/
    - assets/svgs/
    - assets/icons/