name: Build and Deploy Firebase App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.0"
        
    - name: Generate `web.json` file
      run: echo "$WEB_JSON" > ./web/web.json
      env:
        WEB_JSON: ${{ secrets.WEB_JSON }}

    - name: Generate `firebase_options.dart` file
      run: echo "$FIREBASE_OPTIONS_DART" > ./lib/firebase_options.dart
      env:
        FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        
    - name: Getting Latest Packages 
      run: flutter pub outdated
      
    - name: upgrading Packages
      run: flutter pub upgrade
      
    - name: Build Flutter web project
      run: flutter build web

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set up Firebase service account
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > ${{ github.workspace }}/firebase-key.json
      env:
        FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json

